# -*- coding: utf-8 -*-
"""back_end_feedback.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_HWt9nuQtl3Avy6ZDBrZ9lPEMgw56GDB
"""

from flask import Flask, request, jsonify
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from translate import Translator

app = Flask(__name__)
tokenizer = AutoTokenizer.from_pretrained("Kaludi/Reviews-Sentiment-Analysis")
model = AutoModelForSequenceClassification.from_pretrained("Kaludi/Reviews-Sentiment-Analysis")
translator = Translator(to_lang="en", from_lang="id")

@app.route('/predict-sentiment', methods=['POST'])
def predict_sentiment():
    text = request.json['text']

    # Terjemahkan teks ke bahasa Inggris
    translated_text = translator.translate(text)

    # Tokenisasi teks terjemahan
    encoded_input = tokenizer(translated_text, truncation=True, padding=True, return_tensors='pt')

    # Melakukan inferensi menggunakan model
    output = model(**encoded_input)

    # Mengambil prediksi sentimen
    sentiment_pred = output.logits.argmax().item()

    # Menampilkan hasil prediksi
    sentiment_labels = ['Negative', 'Positive']
    predicted_sentiment = sentiment_labels[sentiment_pred]

    return jsonify({'sentiment': predicted_sentiment})

if __name__ == '__main__':
    app.run()